apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: postgres
spec:
  ingressClassName: traefik
  rules:
    - host: postgres.robertharte.net
      http:
        paths:
          - backend:
              service:
                name: postgres
                port:
                  number: 5432
            path: /
            pathType: Prefix
