apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pgadmin
resources:
  - ../../base/pgadmin/
  - pgadmin-container-env-secret.yaml
  - cloudflare-secret.yaml
  - ingress.yaml
