apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wireguard-
spec:
  ingressClassName: traefik
  rules:
    - host: wireguard.robertharte.net
      http:
        paths:
          - backend:
              service:
                name: wireguard
                port:
                  number: 51821
            path: /
            pathType: Prefix
