apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
resources:
  - secret.yaml
  - serviceaccount.yaml
  - service.yaml
  - deployment.yaml
  - configmap.yaml
  - clusterrole.yaml
