apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      containers:
        - name: wireguard
          image: linuxserver/wireguard:latest
          ports:
            - containerPort: 51820
          env:
            - name: "TZ"
              value: "Europe/London"
            # Keep the PEERS environment variable to force server mode
            - name: "PEERS"
              value: "example"
            - name: "PEERDNS"
              value: "8.8.8.8"
          envFrom:
            - secretRef:
                name: wireguard-container-env
          secutiryContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - name: wireguard-data
              mountPath: "/config/"
              readOnly: true
      volumes:
        - name: wireguard-data
          secret:
            secretName: wireguard-container-env
