apiVersion: v1
kind: Service
metadata:
  name: wireguard
spec:
  ports:
    - name: wireguard
      protocol: UDP
      port: 51820
      targetPort: 51820
  selector:
    app: wireguard
  type: ClusterIP
