apiVersion: v1
kind: Service
metadata:
  name: wireguard
spec:
  ports:
    - protocol: UDP
      port: 51820
      targetPort: 51820
      nodePort: 32813
  selector:
    app: wireguard
  type: NodePort
