apiVersion: v1
kind: Namespace
metadata:
  name: database
  labels:
    name: database
---
apiVersion: postgressql.cnpg.io/v1
kind: Cluster
metadata:
  name: demo-cluster
  namespace: database
spec:
  instance: 2
  storage:
    size: 2Gi
